### ISSUE TITLE
Add support for changing Admin URL and Port

### ISSUE THREAD

**Issue by julianxhokaxhiu** [babim/docker-zimbra#1]
Hi,

I really like your Dockerfile and I'm looking forward to start using it. Although I require if possible to change the Admin URL and Port since I don't want to expose the default 7071 port.

To do so, I found [this answer on ServerFault](http://serverfault.com/a/643003) which points on declaring simply two variables: `zimbraAdminPort` and `zimbraAdminURL` to be configurable.

Would be supernice if you can include them to be configured through Docker Run environment variables!

Do you think it's possible? Thanks in advance :)

**Comment by babim** [comment]
hi @julianxhokaxhiu you can use docker map port.
when create docker container -p option
example: -p 8081:7071 (to change 8081 from host to 7071 container)
And no need change everything in zimbra container

**Comment by babim** [comment]
I will test with solution at your link and reply soon. Thanks

**Comment by babim** [comment]
I added
zimbraMailSSLPort="443"
zimbraAdminPort="7071"
zimbraAdminURL="/zimbraAdmin"
in install.sh. You can pull and edit install.sh with your value and build your docker.

Tested and work
Thanks @julianxhokaxhiu for your idea.

**Comment by julianxhokaxhiu** [comment]
Thanks super nice, but ( in my opinion ) there's just one last step missing: please make at least the Port and the Url editable through Environments. So no need to fork your project and create a new docker :)

Eg.

```
docker run \
 -e "ZIMBRA_ADMIN_URL=/admin" \
 -e "ZIMBRA_ADMIN_PORT=443" \
 ...
```

Thanks in advance!

**Comment by babim** [comment]
@julianxhokaxhiu hahaa. You so smart. I can't think about that.
I changed **install.sh** 
_**MailSSLPort1=${MailSSLPort:-443}
AdminPort1=${AdminPort:-7071}
AdminURL1=${AdminURL:-/zimbraAdmin}**_
and **readme.md**
Thanks

**Comment by julianxhokaxhiu** [comment]
Super thank you! I'll try it this evening if possible :)

**Comment by oslnx** [comment]
> Thanks super nice, but ( in my opinion ) there's just one last step missing: please make at least the Port and the Url editable through Environments. So no need to fork your project and create a new docker :)
> 
> Eg.
> 
> ```
> docker run \
>  -e "ZIMBRA_ADMIN_URL=/admin" \
>  -e "ZIMBRA_ADMIN_PORT=443" \
>  ...
> ```
> 
> Thanks in advance!

docker is totally lamer
